# Generated by Django 5.1.1 on 2024-10-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="postimages"),
        ),
    ]
